// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "../interfaces/referrals/IReferralRegistry.sol";

/**
 * @title ReferralRegistry
 * @notice Tracks referral codes, referrer <> referee links, and pays out a
 *         tiered share of trading revenue generated by referred accounts.
 *         `accrueVolume` is called by VariationalPro on every trade settlement;
 *         it looks up the trader's referrer (if any) and credits the
 *         referrer's pending rewards based on their current volume tier.
 */
contract ReferralRegistry is IReferralRegistry, Ownable, ReentrancyGuard {
    using SafeERC20 for IERC20;

    IERC20 public immutable rewardToken; // USDC
    address public variationalPro;

    Tier[] public tiers;

    mapping(bytes32 => address) public codeOwner;
    mapping(address => bytes32) public codeOf;
    mapping(address => address) public referrerOf;
    mapping(address => uint256) public referredVolume; // cumulative referred trading volume
    mapping(address => uint256) public pendingRewards;
    mapping(address => uint256) public totalRewardsPaid;

    function registerCode(bytes32 code) external {
        require(code != bytes32(0), "Referral: empty code");
        require(codeOwner[code] == address(0), "Referral: code taken");
        require(codeOf[msg.sender] == bytes32(0), "Referral: already registered");

        codeOwner[code] = msg.sender;
        codeOf[msg.sender] = code;
        emit ReferrerRegistered(msg.sender, code);
    }

    function linkReferee(address referee, bytes32 code) external {
        require(referrerOf[referee] == address(0), "Referral: already linked");
        address referrer = codeOwner[code];
        require(referrer != address(0), "Referral: unknown code");
        require(referrer != referee, "Referral: self-referral");

        referrerOf[referee] = referrer;
        emit RefereeLinked(referee, referrer, code);
    }

    // ─── Volume accrual (called by VariationalPro on trade settlement) ────

    function accrueVolume(address referee, uint256 volumeUsdc, uint256 revenueUsdc) external onlyVariationalPro {
        address referrer = referrerOf[referee];
        if (referrer == address(0)) return;

        referredVolume[referrer] += volumeUsdc;

        Tier memory tier = currentTier(referrer);
        uint256 reward = (revenueUsdc * tier.shareBps) / 10_000;
        pendingRewards[referrer] += reward;

        emit VolumeAccrued(referrer, referee, volumeUsdc);
    }

    // ─── Claiming ───────────────────────────────────────────────────

    function claimRewards() external nonReentrant returns (uint256 amount) {
        amount = pendingRewards[msg.sender];
        require(amount > 0, "Referral: nothing to claim");

        pendingRewards[msg.sender] = 0;
        totalRewardsPaid[msg.sender] += amount;

        rewardToken.safeTransfer(msg.sender, amount);
        emit RewardPaid(msg.sender, amount);
    }

    // ─── Views ──────────────────────────────────────────────────────

    function currentTier(address referrer) public view returns (Tier memory best) {
        best = tiers[0];
        uint256 volume = referredVolume[referrer];
        for (uint256 i = 0; i < tiers.length; i++) {
            if (volume >= tiers[i].minVolume) {
                best = tiers[i];
            }
        }
    }

    function tierCount() external view returns (uint256) {
        return tiers.length;
    }
}
